{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "promtail.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "promtail.name" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ template "promtail.name" . }}
{{- end }}
