{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "promtail.name" . }}
  name: {{ template "promtail.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

